### ISSUE TITLE
PAY bug when deducting from a non-Checking account.

### ISSUE THREAD

**Issue by AmrElshenawy** [AmrElshenawy/Group-13-NewBank#18]
Test case point of failure:
For customer Bhagy, when creating a Savings account, the command `PAY 2000 SAVINGS CHRISTINA` results in the following error.

![image](https://user-images.githubusercontent.com/57894392/113510831-9b495d00-9554-11eb-95e4-731caa301422.png)

**Comment by amharF** [comment]
Solved with commit 0258f27cc17b14e801bac9c1fb5ccfd3a80058f5; safeguard added to ensure payments can only be made from a user's checking account. Error message given for non-checking account payments instructions
